### ISSUE TITLE
List creation using large list fails with Unicode-related error

### ISSUE THREAD

**Issue by mwobensmith** [mozilla-services/shavar-list-creation#30]
When I attempt to make a Shumway shavar list from a file with 2.7 million URLs, I get the following error:

Traceback (most recent call last):
  File "lists2safebrowsing.py", line 396, in <module>
    main()
  File "lists2safebrowsing.py", line 320, in main
    process_shumway(allowed, chunknum, output_file, log_file)
  File "lists2safebrowsing.py", line 180, in process_shumway
    canon_d = canonicalize(d.encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 16: ordinal not in range(128)

You can view the file I used here:
http://people.mozilla.org/~mwobensmith/tracking_protection/combined_site_list.txt

**Comment by ckolos** [comment]
This is in the shumway list creation... Can you pb/post your shavar.ini file?
