### ISSUE TITLE
Catch requests `ConnectionError` during publish2cloud

### ISSUE THREAD

**Issue by groovecoder** [mozilla-services/shavar-list-creation#93]
The stage job is currently broken trying to access Remote Settings. (See https://bugzilla.mozilla.org/show_bug.cgi?id=1580884) The code should catch the `ConnectionError`s and gracefully execute the rest of the code while logging the error.

**Comment by groovecoder** [comment]
```
Traceback (most recent call last):
  File "lists2safebrowsing.py", line 618, in <module>
    main()
  File "lists2safebrowsing.py", line 591, in main
    publish_to_cloud(config, chunknum)
  File "/home/jenkins/slavehome/workspace/ShavarListCreationStage/publish2cloud.py", line 267, in publish_to_cloud
    config, section, new
  File "/home/jenkins/slavehome/workspace/ShavarListCreationStage/publish2cloud.py", line 125, in new_data_to_publish_to_remote_settings
    record = get_record_remote_settings(config.get(section, 'output'))
  File "/home/jenkins/slavehome/workspace/ShavarListCreationStage/publish2cloud.py", line 77, in get_record_remote_settings
    resp = requests.get(record_url, auth=REMOTE_SETTINGS_AUTH)
  File "/home/jenkins/slavehome/workspace/ShavarListCreationStage/lib/python2.7/site-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/home/jenkins/slavehome/workspace/ShavarListCreationStage/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jenkins/slavehome/workspace/ShavarListCreationStage/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jenkins/slavehome/workspace/ShavarListCreationStage/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/jenkins/slavehome/workspace/ShavarListCreationStage/lib/python2.7/site-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='settings-writer.stage.mozaws.net', port=443): Max retries exceeded with url: /v1/buckets/main-workspace/collections/tracking-protection-lists/records/base-track-digest256 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x4af9850>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```
